### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by PalashCoder** [iamrealpalash/authentecationMethods#2]

**Comment by iamrealpalash** [comment]
import React, { useState, useEffect } from 'react';

const Home = ({ token }) => {
  const [todos, setTodos] = useState([]);
  const [newTodo, setNewTodo] = useState('');

  const fetchTodos = async () => {
    try {
      // Fetch your todo list using a GET request with the token in headers.
      const response = await fetch('your-api-todos-endpoint', {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });
      const data = await response.json();
      if (response.ok) {
        setTodos(data.todos);
      } else {
        console.error(data.message);
      }
    } catch (error) {
      console.error('Error:', error);
    }
  };

  useEffect(() => {
    fetchTodos();
  }, []);

  const addTodo = async () => {
    try {
      // Send a POST request to add a new todo.
      const response = await fetch('your-api-add-todo-endpoint', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ todo: newTodo }),
      });
      const data = await response.json();
      if (response.ok) {
        setTodos([...todos, data.newTodo]);
        setNewTodo('');
      } else {
        console.error(data.message);
      }
    } catch (error) {
      console.error('Error:', error);
    }
  };

  const updateTodo = async (id, updatedText) => {
    try {
      // Send a PUT request to update a todo.
      const response = await fetch(`your-api-update-todo-endpoint/${id}`, {
        method: 'PUT',
        headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ text: updatedText }),
      });
      const data = await response.json();
      if (response.ok) {
        const updatedTodos = todos.map((todo) =>
          todo.id === id ? { ...todo, text: updatedText } : todo
        );
        setTodos(updatedTodos);
      } else {
        console.error(data.message);
      }
    } catch (error) {
      console.error('Error:', error);
    }
  };

  const deleteTodo = async (id) => {
    try {
      // Send a DELETE request to delete a todo.
      const response = await fetch(`your-api-delete-todo-endpoint/${id}`, {
        method: 'DELETE',
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });
      if (response.ok) {
        const updatedTodos = todos.filter((todo) => todo.id !== id);
        setTodos(updatedTodos);
      } else {
        console.error('Error deleting todo');
      }
    } catch (error) {
      console.error('Error:', error);
    }
  };

  return (
    <div>
      <h2>Todo List</h2>
      <input
        type="text"
        placeholder="New Todo"
        value={newTodo}
        onChange={(e) => setNewTodo(e.target.value)}
      />
      <button onClick={addTodo}>Add Todo</button>
      <ul>
        {todos.map((todo) => (
          <li key={todo.id}>
            {todo.text}
            <button onClick={() => updateTodo(todo.id, 'Updated Text')}>
              Update
            </button>
            <button onClick={() => deleteTodo(todo.id)}>Delete</button>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Home;
